name: Build and Dockerize

on:
  push:
    branches: [ "master"]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t mwmpms-server .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag mwmpms-server:latest olooce/mwmpms-server:latest
        docker push olooce/mwmpms-server:latest
