name: Build and Dockerize Java Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t mwmPMS-Server .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag mwmPMS-Server:latest Olooce/mwmPMS-Server:latest
        docker push Olooce/mwmPMS-Server:latest
